---
  - name: Make a folder for this container
    tags:
      - deploy-nginx
    file:
      path: '{{ nginx_path }}'
      state: directory

  - name: 'Copy nginx image setup template files to the remote host'
    tags:
      - deploy-nginx
    template:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
      - { src: 'templates/nginx.conf.j2', dest: '{{ nginx_path }}/nginx.conf' }
      - { src: 'templates/start.j2', dest: '{{ nginx_path }}/start' }
      - { src: 'templates/nginx-rsyslog.conf.j2', dest: '{{ nginx_path }}/nginx-rsyslog.conf' }

  - name: Make the start file executable
    tags:
      - deploy-nginx
    file:
      path: '{{ nginx_path }}/start'
      state: file
      mode: "u=rwx,g=rx"

  - name: Copy remaining nginx image setup files to the remote host
    tags:
      - deploy-nginx
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
      - { src: 'templates/Dockerfile', dest: '{{ nginx_path }}/Dockerfile' }
      - { src: 'templates/nginx.rb', dest: '{{ nginx_path }}/nginx.rb' }
      - { src: 'templates/start-server', dest: '{{ nginx_path }}/start-server' }

  - name: Copy across the http password file for kibana
    tags: 
      - deploy-nginx
    command: "bash -lc \"echo '{{ kibana_creds }}' > {{ nginx_path }}/kibana.htpasswd\""

  - name: Build the nginx + rsyslog docker image
    tags:
      - deploy-nginx
    command: 'bash -lc "cd {{ nginx_path }} && docker build -t {{ nginx_image_name }} ."'

