---
  - name: 'Create new security group: {{ security_group }}'
    tags:
      - create-group
    ec2_group:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'
      name: '{{ security_group }}'
      description: '{{ security_group_desc }}'
      rules:
        - '{{ ssh_proto }}'
        - '{{ http_proto }}'
        - '{{ http_proto_8080 }}'
      rules_egress:
        - '{{ http_proto }}'
        - '{{ http_proto_8080 }}'
        - '{{ https_proto }}'

  - name: 'Remove security group: {{ security_group }}'
    tags:
      - remove-group
    ec2_group:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'
      name: '{{ security_group }}'
      description: '{{ security_group_desc }}'
      state: absent

  - name: Create new keypair
    tags:
      - create-keypair
    ec2_key:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'
      name: '{{ keypair_name }}'
    register: keypair

  - name: Save keypair
    tags:
      - create-keypair
    copy:
      dest: '{{ keypair_path }}/{{ keypair_name }}.pem'
      content: "{{ keypair.key.private_key }}"
      mode: 0600
    when: keypair.changed

  - name: 'Remove keypair'
    tags:
      - remove-keypair
    ec2_key:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'
      name: '{{ keypair_name }}'
      state: absent
