---
instance_type          : m3.medium
security_group         : hyjinx_group
security_group_desc    : Used for webserver hyjinx
image                  : ami-ba3e14d9
region                 : ap-southeast-2
count                  : 1
