---
instance_type          : "m3.medium"
security_group         : "hyjinx_group"
image                  : "ami-ba3e14d9"
region                 : "ap-southeast-2"
aws_access_key         : "{{aws_access_key_minillinim}}"
aws_secret_key         : "{{aws_secret_access_key_minillinim}}"
count                  : 1
