---
base_name              : hyjinx
region                 : ap-southeast-2
keypair_name           : '{{ base_name }}'
keypair_path           : /home/user/.ssh/
security_group         : '{{ base_name }}-group'
security_group_desc    : 'Used for webserver {{ base_name }}'
