---
  - name: Launch EC2 instance
    tags:
      - launch-ec2
    ec2:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      group: '{{ security_group }}'
      key_name: '{{ keypair_name }}'
      instance_type: '{{ instance_type}}'
      image: '{{ image }}'
      wait: true
      region: '{{ region }}'
      count: '{{count}}'
    register: ec2

  - name: Wait for SSH to come up
    tags:
      - launch-ec2
    wait_for:
      host: '{{ item.public_ip }}'
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: '{{ ec2.instances }}'

  - name: Print EC2 instance information
    tags:
      - launch-ec2
    debug:
      msg: 'EC2 instance: {{ item.id }} is up at: {{ item.public_ip }}'
    with_items: '{{ ec2.instances }}'

  - name: Stop EC2 instance
    tags:
      - stop-ec2
    ec2:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      instance_ids: '{{ instance_ids }}'
      region: '{{ region }}'
      state: stopped

  - name: Terminate EC2 instance
    tags:
      - terminate-ec2
    ec2:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      instance_ids: '{{ instance_ids }}'
      region: '{{ region }}'
      state: absent