---
base_name              : hyjinx
keypair_name           : '{{ base_name }}'
security_group         : '{{ base_name }}-group'
instance_type          : m3.medium
image                  : ami-ba3e14d9
region                 : ap-southeast-2
count                  : 1