---
  - name: 'Perform EC2 instance management tasks'
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    vars_files:
      - '{{ inventory_dir }}/group_vars/all/vault.yml'
      - '{{ inventory_dir }}/group_vars/webservers/ec2.yml'
    roles:
      - { role: ec2-instances }

