#!/bin/bash

COLOR_END='\e[0m'
COLOR_RED='\e[0;31m' # Red
COLOR_YEL='\e[0;33m' # Yellow

msg_exit() {
    printf "$COLOR_RED$@$COLOR_END"
    printf "\n"
    printf "Exiting...\n"
    exit 1
}

msg_warning() {
    printf "$COLOR_YEL$@$COLOR_END"
    printf "\n"
}

prompt_confirm() {
  while true; do
    read -r -n 1 -p "${1:-Continue?} [y/n]: " REPLY
    case $REPLY in
      [yY]) echo ; return 0 ;;
      [nN]) echo ; return 1 ;;
      *) printf " \033[31m %s \n\033[0m" "invalid input"
    esac
  done
}

print_usage() {
  echo "usage: ./setup -v|--venv-path <path_to_venv>"
  exit 0
}

TEMP=`getopt -o hv: --long help,venv: -n setup -- "$@"`
[[ $? == 0 ]] || msg_exit "Options parsing failed. Terminating..."

set -e

eval set -- "$TEMP"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_PATH=$(realpath "$DIR/../../")
VENV_PATH=$DIR

while true; do
  case "$1" in
    -v | --venv ) VENV_PATH=`realpath "$2"`; shift 2;;
    -h | --help ) print_usage ; shift; break;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

COLOR_END='\e[0m'
COLOR_RED='\e[0;31m' # Red
COLOR_YEL='\e[0;33m' # Yellow

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
VENV_NAME="python_ansible"
PYTHON_REQUIREMNTS_FILE="$DIR/python_requirements.txt"

msg_exit() {
    printf "$COLOR_RED$@$COLOR_END"
    printf "\n"
    printf "Exiting...\n"
    exit 1
}

msg_warning() {
    printf "$COLOR_YEL$@$COLOR_END"
    printf "\n"
}

prompt_confirm() {
  while true; do
    read -r -n 1 -p "${1:-Continue?} [y/n]: " REPLY
    case $REPLY in
      [yY]) echo ; return 0 ;;
      [nN]) echo ; return 1 ;;
      *) printf " \033[31m %s \n\033[0m" "invalid input"
    esac 
  done  
}

# Check if root
[[ "$(whoami)" == "root" ]] && msg_exit "Please run as a normal user not root"

# Check python 
[[ -z "$(which python)" ]] && msg_exit "Python is not installed or not in your path."
[[ -z "$(which virtualenv)" ]] && msg_exit "Virtualenv is not installed or not in your path."

# Check python file
[[ ! -f "$PYTHON_REQUIREMNTS_FILE" ]]  && msg_exit "python_requirements '$PYTHON_REQUIREMNTS_FILE' does not exist or permssion issue.\nPlease check and rerun."

# last chance
msg_warning "Your system is OK. Will install ansible in a virtual environment at: $VENV_PATH/$VENV_NAME"
prompt_confirm "Install Ansible?" || msg_exit "Terminating..."

# Create venv
virtualenv "$VENV_PATH/$VENV_NAME"

# Switch to this environment
ENABLE_FILE="$PROJECT_PATH/enable"
echo "source $VENV_PATH/$VENV_NAME/bin/activate" > $ENABLE_FILE
echo "export ANSIBLE_ROOT=$PROJECT_PATH" >> $ENABLE_FILE
echo "export ANSIBLE_CONFIG=$PROJECT_PATH/plays/ansible.cfg" >> $ENABLE_FILE
echo "export ANSIBLE_VAULT_PASSWORD_FILE=$PROJECT_PATH/vault.passwd" >> $ENABLE_FILE

. $ENABLE_FILE

# Install requirements
pip install --upgrade pip setuptools
pip install -r "$PYTHON_REQUIREMNTS_FILE"

# Touch vault password file so that things wont instantly break
touch "$PROJECT_PATH/vault.passwd"

msg_warning "Setup complete. Type: source $PROJECT_PATH/enable to begin using Ansible"

exit 0
